-- BD UNIVERSIDADE

DROP DATABASE IF EXISTS UNIVERSIDADE;
CREATE DATABASE IF NOT EXISTS UNIVERSIDADE;
USE UNIVERSIDADE;

CREATE TABLE IF NOT EXISTS PROFESSOR (
    ID_PROFESSOR INT NOT NULL PRIMARY KEY,
    SOBRENOME VARCHAR(25),
    NOME VARCHAR(25),
    PRONTUARIO CHAR(7)
);

CREATE TABLE IF NOT EXISTS AREA (
    ID_AREA VARCHAR(4) NOT NULL PRIMARY KEY,
    NOME VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS CURSO (
    ID_CURSO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    COD_AREA VARCHAR(4) NOT NULL,
    FOREIGN KEY(COD_AREA)
		REFERENCES AREA (ID_AREA)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALUNO (
    ID_ALUNO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(25),
    PRONTUARIO CHAR(7),
    COD_CURSO INT NOT NULL,
    FOREIGN KEY(COD_CURSO)
		REFERENCES CURSO(ID_CURSO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DISCIPLINA (
    ID_DISCIPLINA VARCHAR(10) NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    DESCRICAO VARCHAR(50),
    COD_CURSO INT NOT NULL,
    COD_PROFESSOR INT NOT NULL,
    ANO VARCHAR (10),
    FOREIGN KEY(COD_CURSO)
		REFERENCES CURSO(ID_CURSO)
        ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(COD_PROFESSOR)
		REFERENCES PROFESSOR(ID_PROFESSOR)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DISCIPLINA_TURMA (
	ID_TURMA INT NOT NULL PRIMARY KEY,
    NUM_TURMA INT NOT NULL,
    COD_DISCIPLINA VARCHAR(10) NOT NULL,
    COD_ALUNO INT NOT NULL,
    FOREIGN KEY(COD_DISCIPLINA)
		REFERENCES DISCIPLINA(ID_DISCIPLINA)
        ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(COD_ALUNO)
		REFERENCES ALUNO(ID_ALUNO)
        ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO PROFESSOR VALUES(01,'BELUZO','JOSÉ',1805070);
INSERT INTO PROFESSOR VALUES(02,'CRISCUOLO','MARCELO',1805071);
INSERT INTO PROFESSOR VALUES(03,'BRANCO','LUIZ',1805072);
INSERT INTO PROFESSOR VALUES(04,'PORTO','RENATA',1805073);

INSERT INTO AREA VALUES('TI','INFORMATICA');
INSERT INTO AREA VALUES('EC','ENGENHARIA DA COMPUTAÇÃO');
INSERT INTO AREA VALUES('EE','ENGENHARIA ELETRICA');
INSERT INTO AREA VALUES('EM','ENGENHARIA MECANICA');


INSERT INTO CURSO VALUES(01,'TECNICO EM INFORMATICA','TI');
INSERT INTO CURSO VALUES(02,'ANALISE E DESENVOLVIMENTO DE SISTEMAS','EC');
INSERT INTO CURSO VALUES(03,'ELETRICA BÁSICA','EE');
INSERT INTO CURSO VALUES(04,'MANUTENÇÃO DE MAQUINAS','EM');


INSERT INTO ALUNO VALUES(70,'CAIO',1805080,01);
INSERT INTO ALUNO VALUES(71,'NATIELLE',1805081,01);
INSERT INTO ALUNO VALUES(72,'GUILHERME',1805082,01);
INSERT INTO ALUNO VALUES(73,'EVELYN',1805083,01);


INSERT INTO DISCIPLINA VALUES('DDS','DESENVOLVIMENTO DE SISTEMAS','DESENVOLVER SISTEMAS',01,01,'2° ANO');
INSERT INTO DISCIPLINA VALUES('ADB','ADMINSTRAÇÃO DE BANCO DE DADOS','DESENVOLVER SISTEMAS',01,04,'2° ANO');
INSERT INTO DISCIPLINA VALUES('RDC','REDES DE COMPUTADORES','ESTUDAR REDE DE COMPUTADORES',01,03,'2° ANO');
INSERT INTO DISCIPLINA VALUES('PDIW','PROGRAMAÇÃO DE INTERFACE WEB','PROGRAMAÇÃO EM WEB',01,02,'2° ANO');


INSERT INTO DISCIPLINA_TURMA VALUES(180,12,'DDS',72);

SELECT * 
FROM DISCIPLINA_TURMA;

SELECT *
FROM PROFESSOR;

SELECT *
FROM DISCIPLINA;

SELECT *
FROM ALUNO;

SELECT *
FROM CURSO;

SELECT *
FROM AREA;